### ISSUE TITLE
关于文字识别模块中的损失函数计算

### ISSUE THREAD

**Issue by xiliu** [HLIG/HUAWEIOCR-2019#1]
你好，在仔细学习过你们的说明文档(https://discussion.datafountain.cn/questions/1571)后，还是有两点不太明白，可否给些详细的说明。
1，损失函数中的权重w具体是怎么计算得到的？
2，损失函数中的labels是(bs,1,162,9115)大小吗？怎么得到的？

非常期待你的回复，谢谢。

**Comment by dhKwang** [comment]
> 你好，在仔细学习过你们的说明文档([https://discussion.datafountain.cn/questions/1571)后，还是有两点不太明白，可否给些详细的说明。](https://discussion.datafountain.cn/questions/1571)%E5%90%8E%EF%BC%8C%E8%BF%98%E6%98%AF%E6%9C%89%E4%B8%A4%E7%82%B9%E4%B8%8D%E5%A4%AA%E6%98%8E%E7%99%BD%EF%BC%8C%E5%8F%AF%E5%90%A6%E7%BB%99%E4%BA%9B%E8%AF%A6%E7%BB%86%E7%9A%84%E8%AF%B4%E6%98%8E%E3%80%82)
> 1，损失函数中的权重w具体是怎么计算得到的？
> 2，损失函数中的labels是(bs,1,162,9115)大小吗？怎么得到的？
> 
> 非常期待你的回复，谢谢。

1.非困难样本挖掘的时候，权重的计算是使用`main.py`中426行的`get_weight`函数获取，大致思路是统计一次训练的样本中未出现的字符数（负样本数）和出现字符数（正样本数）的比例构建权重矩阵。

**Comment by HLIG** [comment]
> 你好，在仔细学习过你们的说明文档([https://discussion.datafountain.cn/questions/1571)后，还是有两点不太明白，可否给些详细的说明。](https://discussion.datafountain.cn/questions/1571)%E5%90%8E%EF%BC%8C%E8%BF%98%E6%98%AF%E6%9C%89%E4%B8%A4%E7%82%B9%E4%B8%8D%E5%A4%AA%E6%98%8E%E7%99%BD%EF%BC%8C%E5%8F%AF%E5%90%A6%E7%BB%99%E4%BA%9B%E8%AF%A6%E7%BB%86%E7%9A%84%E8%AF%B4%E6%98%8E%E3%80%82)
> 1，损失函数中的权重w具体是怎么计算得到的？
> 2，损失函数中的labels是(bs,1,162,9115)大小吗？怎么得到的？
> 
> 非常期待你的回复，谢谢。

2.损失函数中的labels是（bs,1,1,9115）。groundtruth的标签，是图片中的汉字，（bs,1,1,9115），图片中有这个字，(1,1,9115)对应的地方就有1。（bs,64,1300,3）的图片经过经过densenet后特征图大小为（bs,8,162,9115），然后对8和162的维度取最大（即每个字取最大值），得到（bs,1,1,9115），然后和上面groundtruth中的标签进行损失计算。

**Comment by xiliu** [comment]
感谢二位的详细解答，关于之前的两个问题清楚了。

现在有两个新的问题，请教下：
    1，该模型训练在没有字符（单个字）位置信息情况监督下，但可以在解码后可额外获得单字的位置信息，确实了得。那么该方案是否可以推广到整张图片（含多行文本，且比较稀疏）？而不只是含有单行文本的图像。
    2，打算用inception-resnet-v2作为特征提取网络，重新训练，有什么建议吗？或有什么可能会踩的坑？

谢谢

**Comment by HLIG** [comment]
1、感觉对8和162的维度取最大的过程中，引入了位置信息，在样本充足的情况下，就学到了位置信息。对整张图片应该是可以的，需要用文本检测的方法将单行/列文本分割出来。现在的文本识别几乎都是针对检测出来的每个单行/列文本进行识别（先定位再识别）。
2、没试过，建议样本多一些，多查资料。

**Comment by HLIG** [comment]
@xiliu 1、应该是对8和162的维度取最大的过程中，引入了位置信息，样本足够的情况下就学到了位置信息。对整张图片应该是可以的，需要用文本检测的方法将行/列文本分割出来。现在的文本识别几乎都是针对检测出来的行/列文本进行识别（先定位再识别）。
2。没试过，建议样本多一些，多查资料。

**Comment by xiliu** [comment]
@HLIG 谢谢，祝好
