### ISSUE TITLE
recognition.txt的相关问题

### ISSUE THREAD

**Issue by WonDaniel** [HLIG/HUAWEIOCR-2019#3]
pip install recognition.txt报错，是否应该是pip install -r recognition.txt，而且里面，例如backports-functools-lru-cache=1.5=pypi_0，提示“= is not a valid operator. Did you mean == ?”，所以是否是需要把所有“=”改为“==”，改了也说没有1.5的版本，所以...
@HLIG

**Comment by HLIG** [comment]
嗯嗯，是的，应该是pip install -r recognition.txt。
你也可以试一下conda create --name recognition --file recognition.txt
如果某个版本出错，可以试一下除了指定主要的python,pytorch包版本之外，其他的报错的包尝试不指定版本安装，让环境自己给你找合适的版本
如直接在环境中执行pip/conda install +包名如numpy。backports-functools-lru-cache，certifi，ca-certificates是打包的时候自己弹出来的，不安装程序也可以运行。
pip/conda install +以下
decorator
functools32
fuzzywuzzy
kiwisolver
libedit
libffi
libgcc-ng
libstdcxx-ng
lxml
matplotlib
ncurses
networkx
numpy
openssl
pandas
pillow
pip
py
pyparsing
pytest
python=2.7.16
python-dateutil
pytils
pytz
pywavelets
readline
scikit-image
scikit-learn
scipy
setuptools
six
sqlite
subprocess32
tk
tools
torch=1.0.1
torchvision=0.2.0
tqdm
wheel
zlib
